// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class DeletePostTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    String userName = "zlodthctutlkx";

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void deletePost() throws InterruptedException {
        Util.login(driver, userName);
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")));
        }
        driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")).click();
        int old = Integer.parseInt(driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/div/div/div/ul[2]/div/li/div/ul/li[1]/a/span[2]")).getText());
        driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div/header/div[2]/div[6]/span/div/div/div/ul[2]/div/li/div/ul/li/a")).click();

        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"base-container\"]/div[2]/div[2]/div[1]/main/div[2]/div[2]/div[1]/div/div/article/div[2]/footer/div[2]/div[4]/button")));
        }

        driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[2]/div[1]/main/div[2]/div[2]/div[1]/div/div/article/div[2]/footer/div[2]/div[4]/button")).click();
        driver.findElement(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div[2]/button[2]/span")).click();
        TimeUnit.SECONDS.sleep(3);
        driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")).click();
        driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div/header/div[2]/div[6]/span/div/div/div/ul[2]/div/li/div/ul/li/a")).click();
        driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")).click();
        int new_str = Integer.parseInt(driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/div/div/div/ul[2]/div/li/div/ul/li[1]/a/span[2]")).getText());
        Assertions.assertEquals(1, old - new_str);

    }
}
