// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class LoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }


    @Test
    public void login() {

        String userName = "zlodthctutlkx";
        Util.login(driver, userName);
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'base-container\']/div[2]/div[2]/div/main/div[3]/div/div/span/span/a/div/div/div/img")));
        }
        driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div[2]/div/main/div[3]/div/div/span/span/a/div/div/div/img")).click();
        vars.put("window_handles", driver.getWindowHandles());
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div/div/div/div/header/div/a/div[2]")));
        }
        driver.findElement(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div/div/div/div/header/div/a/div[2]")).click();
        vars.put("win4955", waitForWindow(2000));
        driver.switchTo().window(vars.get("win4955").toString());
        String s = driver.getCurrentUrl();
        String ss[] = s.split("[.]");
        Assertions.assertEquals(ss[0].substring(8), userName);
    }
}
