// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String userName = "zlodthctutlkx";
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logout() {
    driver.get("https://www.tumblr.com/dashboard");
    Util.login(driver, userName);
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")));
    }
    driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")).click();
    driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div/header/div[2]/div[6]/span/div/div/div/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div[2]/button[2]/span")).click();
  }
}
