// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MakePostTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String userName = "zlodthctutlkx";
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    Util.login(driver, userName);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("https://www.tumblr.com/dashboard");
    driver.findElement(By.cssSelector("li:nth-child(1) > .\\_3KQTj path")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.id("3")));
    }
    driver.switchTo().frame(3);
    driver.findElement(By.xpath("//body[@id=\'redpop_iframePostForms\']/div[3]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div/div[5]/div[2]/div[5]")).click();
    driver.findElement(By.xpath("//body[@id=\'redpop_iframePostForms\']/div[3]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div/div")).click();
    driver.findElement(By.xpath("//body[@id=\'redpop_iframePostForms\']/div[3]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div/div/p[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//body[@id=\'redpop_iframePostForms\']/div[3]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div/div"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"fake\"><br></p><div class=\"media-holder media-holder-draggable media-holder-hr\" contenteditable=\"false\" draggable=\"true\"><hr class=\"tmblr-truncated\" data-label=\"Keep reading\"><div class=\"media-button icon_close media-killer\"></div></div><p style=\"\">оыфвлдодлфВЫЛФВЛЖ</p>'}", element);
    }
    driver.findElement(By.xpath("//body[@id=\'redpop_iframePostForms\']/div[3]/div/div/div/div/div[2]/div[2]/div/div[5]/div/div/div[3]/div/div/button")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.xpath("//*[@id=\"base-container\"]/div[2]/div[1]/header/div[2]/div[6]/span/span/button")).click();
    driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div/header/div[2]/div[6]/span/div/div/div/ul[2]/div/li/div/ul/li/a/span")).click();
  }
}
