// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class SignupTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void signup() {
        String userName = Util.generateString(13);
        driver.get("https://www.tumblr.com/");
        driver.findElement(By.xpath("//div[2]/a[2]")).click();
        driver.findElement(By.xpath("//input[@name=\'email\']")).sendKeys(userName + "@gmail.com");
        driver.findElement(By.xpath("//input[@name=\'password\']")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("HelloFella420!");
        driver.findElement(By.xpath("//input[@name=\'blogName\']")).click();
        driver.findElement(By.xpath("//input[@name=\'blogName\']")).sendKeys(userName);
        driver.findElement(By.xpath("//section[@id=\'Get started\']/div/div/div[2]/div/section/div/form/button/span")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//input[@name=\'age\']")));
        }
        driver.findElement(By.xpath("//input[@name=\'age\']")).sendKeys("17");
        driver.findElement(By.xpath("//input[@type=\'checkbox\']")).click();
        driver.findElement(By.xpath("//section[@id=\'Get started\']/div/div/div[2]/div/section/div/form/button/span")).click();
        try {
            {
                WebDriverWait wait = new WebDriverWait(driver, 10);
                wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//button/div")));
            }
            driver.findElement(By.xpath("//button/div")).click();
        } catch (Exception e) {
            System.out.println("Continuing");
        }
        System.out.println(userName);
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'base-container\']/div[2]/div[2]/div/main/div[3]/div/div/span/span/a/div/div/div/img")));
        }
        driver.findElement(By.xpath("//div[@id=\'base-container\']/div[2]/div[2]/div/main/div[3]/div/div/span/span/a/div/div/div/img")).click();
        vars.put("window_handles", driver.getWindowHandles());
        {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div/div/div/div/header/div/a/div[2]")));
        }
        driver.findElement(By.xpath("//div[@id=\'glass-container\']/div/div[2]/div/div/div/div/header/div/a/div[2]")).click();
        vars.put("win4955", waitForWindow(2000));
        driver.switchTo().window(vars.get("win4955").toString());
        String s = driver.getCurrentUrl();
        String ss[] = s.split("[.]");
        Assertions.assertEquals(ss[0].substring(8), userName);
    }
}
